"""Add InterconsultaPedido

Revision ID: eccfa4ee91c7
Revises: 8a2efbe37bb6
Create Date: 2026-05-24 14:19:42.890508

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eccfa4ee91c7'
down_revision: Union[str, Sequence[str], None] = '8a2efbe37bb6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('interconsulta_pedidos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('paciente_cns', sa.String(), nullable=False),
    sa.Column('medico_solicitante_crm', sa.String(), nullable=False),
    sa.Column('especialidade_id', sa.Integer(), nullable=False),
    sa.Column('sintomas_json', sa.JSON(), nullable=False),
    sa.Column('gravidade', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.Column('atualizado_em', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interconsulta_pedidos_id'), 'interconsulta_pedidos', ['id'], unique=False)
    op.create_index(op.f('ix_interconsulta_pedidos_paciente_cns'), 'interconsulta_pedidos', ['paciente_cns'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('token', sa.String(), nullable=True),
    sa.Column('groups', sa.JSON(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refresh_tokens_id'), 'refresh_tokens', ['id'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_token'), 'refresh_tokens', ['token'], unique=True)
    op.create_index(op.f('ix_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_refresh_tokens_user_id'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_token'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_id'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index(op.f('ix_interconsulta_pedidos_paciente_cns'), table_name='interconsulta_pedidos')
    op.drop_index(op.f('ix_interconsulta_pedidos_id'), table_name='interconsulta_pedidos')
    op.drop_table('interconsulta_pedidos')
    # ### end Alembic commands ###
